import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head'
import { Header } from '../app/components';
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { About } from '../app/components/layouts/About';

const Home: NextPage = () => {

  return (
    <div >
      <Head>
        <title>Mina Yaghoubi kia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <About/>
    </div>
  )
}

export default Home;

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale || "en", ["common", "header", "about"])),
      // Will be passed to the page component as props
    },
  };
}
