import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head'
import { HeaderContainer } from '../components';
import { useRouter } from 'next/router';
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

const Home: NextPage = () => {
  const router = useRouter()
  const { pathname, asPath, query, locale } = router;
  const getNextLocal = () => {
    return locale === 'en' ? 'fa' : 'en';
  }

  return (
    <div >
      <Head>
        <title>Mina Yaghoubi kia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
      onClick={() => {
        router.push({ pathname, query }, asPath, { locale: getNextLocal() })

      }}
    >
      {getNextLocal()}
    </div>
      <HeaderContainer/>
    </div>
  )
}

export default Home;

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale || "en", ["common", "header"])),
      // Will be passed to the page component as props
    },
  };
}
